version: '3.8'

name: slack-clone-backend-test

services:
  slack_clone_test_postgres:
    image: postgres:alpine
    container_name: slack_clone_test_postgres
    restart: 'no'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5444:5432' # Different port to avoid conflict with the development environment
    volumes:
      - slack_clone_test_postgres:/var/lib/postgresql/data

  slack_clone_test_redis:
    image: redis:alpine
    container_name: slack_clone_test_redis
    ports:
      - '6380:6379' # Different port to avoid conflict with the development environment
    volumes:
      - slack_clone_test_redis:/data

networks:
  default:
    name: nestjs_starter_test

volumes:
  slack_clone_test_postgres: # Needs to be the same as the volume name in the postgres service
  slack_clone_test_redis: # Needs to be the same as the volume name in the redis service
